### 서블릿 ###
# HTTP 요청 데이터 - API 메시지 바디 - 단순 텍스트
POST http://localhost:8080/request-body-string
Content-Type: text/plain
Accept: application/json

"hello!"

###
# HTTP 요청 데이터 - API 메시지 바디 - JSON
POST http://localhost:8080/request-body-json
Content-Type: application/json
Accept: application/json

{
  "username": "hello",
  "age": 20
}